---

- name: "install : python-{{ python_version }}"
  apt:
    cache_valid_time: 3600
    name:
      - "python3"
      - "python-setuptools"
    state: "{{ python_apt_state }}"

- name: "install : python-pip3"
  apt:
    cache_valid_time: 3600
    name:
      - "python3-pip"
    state: "{{ python_apt_state }}"

